version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.0

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          filters:
            tags:
              only: /.*/

      - orb-tools/review:
          exclude: "RC009"
          filters:
            tags:
              only: /.*/

      - shellcheck/check:
          exclude: 'SC2148,SC2038,SC2086,SC2002,SC2016'
          filters:
            tags:
              only: /.*/

      - bats/run:
          path: ./src/tests
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check, bats/run]
          context: orb-publishing
          orb-name: cyber4all/orb
          vcs-type: << pipeline.project.type >>
          filters:
            tags:
              only: /.*/

      - orb-tools/continue:
          requires:
            - orb-tools/publish
          vcs-type: << pipeline.project.type >>
          pipeline-number: << pipeline.number >>
          filters:
            tags:
              only: /.*/
