version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.1.0
  cyber4all: cyber4all/orb@2.1.2

workflows:
  release:
    jobs:
      # ----------------- Continuous Integration -----------------

      # Lints the yaml files
      - orb-tools/lint

      # Compiles orb
      - orb-tools/pack

      # Checks circleci rules
      - orb-tools/review:
          exclude: 'RC009'

      # ----------------- Auto-Tag (Pre-release) -----------------

      # Automatically tags the orb with the version
      # defined in the VERSION file.
      # Use the ./version.sh script to update the version.
      # Use the -w flag to write the version to the file.
      - cyber4all/release:
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          context: Github
          tag: $(./version.sh -r)
          filters:
            branches:
              only: main
      
      # ----------------- Production -----------------

      # Packs the orb for production
      - orb-tools/pack:
          name: pack-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
  
      # Publishes orb to circleci registry
      - orb-tools/publish:
          requires:
            - pack-prod
          context: 
            - orb-publishing
            - Github
          orb_name: cyber4all/orb
          pub_type: production
          vcs_type: <<pipeline.project.type>>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
