version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.0
  cyber4all: cyber4all/orb@1.3.0

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          name: pack-test
      - orb-tools/review:
          exclude: 'RC009'
      - shellcheck/check:
          exclude: 'SC2148,SC2038,SC2086,SC2002,SC2016'
      - bats/run:
          path: ./src/tests
          
      - cyber4all/release:
          requires:
            [orb-tools/lint, orb-tools/review, pack-test, shellcheck/check, bats/run]
          context: [Github]
          tag: $(./version.sh -r)
          filters:
            branches:
              only: releases

      # publish orb to production
      - orb-tools/pack:
          name: pack-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
 
      - orb-tools/publish:
          requires:
            [pack-prod]
          context: orb-publishing
          orb-name: cyber4all/orb
          enable-pr-comment: false
          pub-type: production
          vcs-type: <<pipeline.project.type>>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
