version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.6
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.1
  cyber4all: cyber4all/orb@1.3.12

workflows:
  lint-pack:
    jobs:
      # lints the yaml files
      - orb-tools/lint

      # compiles orb
      - orb-tools/pack

      # checks circleci rules
      - orb-tools/review:
          exclude: 'RC009'

      # lints shell scripts
      - shellcheck/check:
          exclude: 'SC2148,SC2038,SC2086,SC2002,SC2016'

      # runs bat tests
      - bats/run:
          path: ./src/tests
      
      # automate github tagged release
      - cyber4all/release:
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check, bats/run]
          context: Github
          tag: $(./version.sh -r)
          filters:
            branches:
              only: releases
  
      # publishes orb to circleci registry
      - orb-tools/publish:
          requires:
            [orb-tools/pack]
          context: orb-publishing
          orb-name: cyber4all/orb
          enable-pr-comment: false
          pub-type: production
          vcs-type: <<pipeline.project.type>>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
