version: 2.1

orbs:
  orb: 'cyber4all/orb@dev:<<pipeline.git.revision>>'
  orb-tools: circleci/orb-tools@11.1

jobs:
  command-tests:
    docker:
      - image: 'cimg/base:current'
    steps:
      - checkout

workflows:
  test-deploy:
    jobs:
      # test our commands
      - command-tests:
          filters:
            tags:
              only: /.*/
      # test our jobs

      # publish orb to production
      - orb-tools/pack:
          filters:
            branches:
              ignore: /.*/
              only: releases
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
 
      - orb-tools/publish:
          requires:
            [orb-tools/pack]
          context: orb-publishing
          orb-name: cyber4all/orb
          enable-pr-comment: false
          pub-type: production
          vcs-type: <<pipeline.project.type>>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
